### ISSUE TITLE
Problem to build horovod (horovod/torch/tensor_util.cc:39:30: error: ‘THByteTensor_newSizeOf’ was not declared in this scope)

### ISSUE THREAD

**Issue by labor00** [uber/horovod#446]
Hello. I was trying to build the Horovod library and I got this error when compiling the Horovod with the pytorch from the master brach of its repository. However I was able to compile the Horovod using pytorch 0.4.1, Is there any workaround besides working with the 0.4.1 ?
thanks
```bash
tensor_util.cc: In static member function ‘static void horovod::torch::TensorUtil::CopyCPUToCuda(T*, TC*) [with horovod::common::MPIDataType DT = (horovod::common::MPIDataType)0; T = THTensor; TC = THTensor]’:
/home/disk0/.pytorch/horovod/horovod/torch/tensor_util.cc:39:30: error: ‘THByteTensor_newSizeOf’ was not declared in this scope
                              THByteTensor, THCudaByteStorage)

/home/disk0/.pytorch/horovod/horovod/torch/tensor_util.cc:38:58: error: ‘THCudaByteTensor_isSize’ was not declared in this scope

/home/disk0/.pytorch/horovod/horovod/torch/tensor_util.cc:39:30: error: ‘THByteTensor_isSize’ was not declared in this scope
                              THByteTensor, THCudaByteStorage)
 TENSOR_UTIL_DEFINE_CUDA_TYPE(MPIDataType::HOROVOD_UINT8, THCudaByteTensor,
```

**Comment by alsrgv** [comment]
@labor00, could you check whether #458 fixes your issue?

**Comment by labor00** [comment]
Sorry for the delay, but it was fixed by this commit
